"""初始迁移：scheduler_state表

Revision ID: 766c657a5db8
Revises: 
Create Date: 2026-03-30 07:53:39.765655

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766c657a5db8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_state',
    sa.Column('job_name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('last_run_time', sa.DateTime(), nullable=True, comment='最近运行时间'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='运行状态'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_state')
    # ### end Alembic commands ###
