"""添加watchlist_group和analysis_record表

Revision ID: f35b7fc8e3b8
Revises: 766c657a5db8
Create Date: 2026-03-30 11:13:27.546194

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35b7fc8e3b8'
down_revision: Union[str, None] = '766c657a5db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_record',
    sa.Column('stock_code', sa.String(length=16), nullable=False, comment='股票代码'),
    sa.Column('analysis_date', sa.Date(), nullable=False, comment='分析日期'),
    sa.Column('group_name', sa.String(length=64), nullable=False, comment='所属分组'),
    sa.Column('result_json', sa.Text(), nullable=False, comment='分析结果 JSON'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_record_analysis_date'), 'analysis_record', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_analysis_record_stock_code'), 'analysis_record', ['stock_code'], unique=False)
    op.create_table('watchlist_group',
    sa.Column('name', sa.String(length=64), nullable=False, comment='分组名称'),
    sa.Column('description', sa.String(length=256), nullable=False, comment='分组描述'),
    sa.Column('strategy', sa.String(length=64), nullable=False, comment='分析策略'),
    sa.Column('push_frequency', sa.String(length=32), nullable=False, comment='推送频率'),
    sa.Column('stocks_json', sa.Text(), nullable=False, comment='股票代码列表 JSON'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_group')
    op.drop_index(op.f('ix_analysis_record_stock_code'), table_name='analysis_record')
    op.drop_index(op.f('ix_analysis_record_analysis_date'), table_name='analysis_record')
    op.drop_table('analysis_record')
    # ### end Alembic commands ###
